spring:
  application:
    name: valore
  datasource:
    url: jdbc:postgresql://localhost:5432/valore?currentSchema=valore
    driver-class-name: org.postgresql.Driver
    username: valore_user
    password: V97862345789
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        default_schema: valore
  thymeleaf:
    cache: false

server:
  port: 8080
