spring:
  application:
    name: valore
  datasource:
    url: jdbc:postgresql://localhost:5432/valore
    driver-class-name: org.postgresql.Driver
    username: valore_user
    password: V97862345789
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false

server:
  port: 8080
